export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNUP_FAIL="SIGNUP_FAIL";
export const SIGNIN_FAIL="SIGNIN_FAIL";
export const USER_LOADED="USER_LOADED";
export const USER_LOAD_FAIL="USER_LOAD_FAIL"



