export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNUP_FAIL="SIGNUP_FAIL";
export const SIGNIN_FAIL="SIGNIN_FAIL";
export const USER_LOADED="USER_LOADED";
export const USER_LOAD_FAIL="USER_LOAD_FAIL"
export const LOGOUT="LOGOUT";


export const SUMMARY_LOADED="SUMMARY_LOADED";
export const SUMMARY_LOAD_ERROR="SUMMARY_LOAD_ERROR";


export const OPEN_MODAL="OPEN_MODAL";
export const CLOSE_MODAL="CLOSE_MODAL";

export const ADD_TRANSACTION="ADD_TRANSACTION";
export const ADD_TRANSACTION_ERROR="ADD_TRANSACTION_ERROR";


export const GET_TRANSACTIONS="GET_TRANSACTIONS";







